title: Yang yazhao's Homepage
page-top-title: Yang yazhao
top-section-bg-text: Computer Science
home-subtitle: Yang yazhao&ensp;|&ensp;杨亚召
copyright-text: '&copy; Yang yazhao 2025-2026. All Rights Reserved.'
